export interface TourPackage {
  slug: string;
  name: string;
  destination: string;
  country: string;
  region: "Yurt İçi" | "Avrupa" | "Orta Doğu" | "Uzak Doğu" | "Afrika" | "Amerika";
  duration: string;
  nights: number;
  price: number;
  oldPrice?: number;
  currency: "TRY" | "EUR" | "USD";
  badge?: "Bestseller" | "Yeni" | "İndirim" | "Son Kontenjan";
  rating: number;
  reviews: number;
  summary: string;
  description: string;
  included: string[];
  excluded: string[];
  highlights: string[];
  availableDates: string[];
  gallery: string[]; // placeholder labels
  faq: { q: string; a: string }[];
  groupSize: string;
  difficulty: "Kolay" | "Orta" | "Aktif";
}

export const TOURS: TourPackage[] = [
  {
    slug: "kapadokya-balon",
    name: "Kapadokya Balon & Kültür Turu",
    destination: "Kapadokya",
    country: "Türkiye",
    region: "Yurt İçi",
    duration: "3 Gece / 4 Gün",
    nights: 3,
    price: 12800,
    currency: "TRY",
    badge: "Bestseller",
    rating: 4.9,
    reviews: 142,
    summary: "Peribacaları, balon turu ve yeraltı şehirleriyle Kapadokya'nın büyüsü.",
    description: "Türkiye'nin en ikonik destinasyonlarından Kapadokya'yı en iyi şekilde deneyimleyin. Şafak vakti sıcak hava balonu, tarihi kilise resimleri, yeraltı şehirleri ve eşsiz doğa manzaralarıyla dolu 4 gün.",
    included: ["Uçak bileti (gidiş-dönüş)", "3 gece otel (üst düzey mağara otel)", "Sabah kahvaltıları", "Sıcak hava balonu turu", "Profesyonel Türkçe/İngilizce rehber", "Tüm transferler"],
    excluded: ["Öğle ve akşam yemekleri", "Kişisel harcamalar", "İsteğe bağlı aktiviteler"],
    highlights: ["Şafak vakti balon turu", "Göreme Açık Hava Müzesi", "Yeraltı Şehri Derinkuyu", "Ihlara Vadisi yürüyüşü"],
    availableDates: ["15 Nisan 2026", "22 Nisan 2026", "6 Mayıs 2026", "20 Mayıs 2026", "3 Haziran 2026"],
    gallery: ["Balon Turu — Gün Doğumu", "Göreme Vadisi Panorama", "Mağara Otel İç Mekan", "Peribacaları"],
    faq: [
      { q: "Balon turu hava durumuna bağlı mı?", a: "Evet. Olumsuz hava koşullarında balon turu iptal edilebilir; bu durumda ücreti iade edilir veya başka bir güne ertelenir." },
      { q: "Uçuş hangi havalimanından?", a: "İstanbul Sabiha Gökçen'den Kayseri'ye direkt uçuş. Ankara'dan da kalkış seçeneği mevcuttur." },
    ],
    groupSize: "Maks. 16 kişi",
    difficulty: "Kolay",
  },
  {
    slug: "santorini-balayı",
    name: "Santorini Balayı & Romantik Kaçış",
    destination: "Santorini",
    country: "Yunanistan",
    region: "Avrupa",
    duration: "5 Gece / 6 Gün",
    nights: 5,
    price: 1150,
    oldPrice: 1380,
    currency: "EUR",
    badge: "İndirim",
    rating: 4.9,
    reviews: 87,
    summary: "Mavi kubbeler, Oia günbatımı ve eşsiz Ege manzarasıyla unutulmaz balayı.",
    description: "Santorini'nin simgesi olan beyaz badanalı evler, mavi kubbeli kiliseler ve dramatik kaldera manzarası eşliğinde 5 gecelik romantik kaçış. Oia köyü, Fira sokaklarının keşfi ve katamaran turu dahildir.",
    included: ["Uçak bileti", "Ada transferleri (feribot dahil)", "5 gece butik otel (sonsuzluk havuzlu)", "Günlük kahvaltı", "Özel katamaran turu", "Rehber"],
    excluded: ["Yemekler (kahvaltı hariç)", "Scooter kiralama", "Tekil aktiviteler"],
    highlights: ["Oia günbatımı seyri", "Katamaran deniz turu", "Fira & Imerovigli yürüyüşü", "Volkanik plaj ziyareti"],
    availableDates: ["1 Mayıs 2026", "8 Mayıs 2026", "22 Mayıs 2026", "5 Haziran 2026"],
    gallery: ["Oia Günbatımı", "Sonsuzluk Havuzu Manzarası", "Katamaran Turu", "Fira Sokakları"],
    faq: [
      { q: "Balayı çiftlere özel süprizler var mı?", a: "Evet. Oda süsleme, şampanya ve romantik akşam yemeği reservasyonu talep üzerine düzenlenir." },
    ],
    groupSize: "Çift odası (maks. 2 kişi)",
    difficulty: "Kolay",
  },
  {
    slug: "bali-ruhani-yolculuk",
    name: "Bali — Tapınaklar, Pirinç Tarlaları & Plajlar",
    destination: "Bali",
    country: "Endonezya",
    region: "Uzak Doğu",
    duration: "7 Gece / 8 Gün",
    nights: 7,
    price: 1850,
    currency: "EUR",
    badge: "Yeni",
    rating: 4.8,
    reviews: 54,
    summary: "Ubud orman villaları, Hindu tapınakları ve Seminyak plajlarıyla Bali'nin tinsel ve doğal güzellikleri.",
    description: "Bali'nin en özgün deneyimlerini yaşayın: Ubud'un pirinç terası yürüyüşleri, Tanah Lot ve Uluwatu tapınak ziyaretleri, geleneksel Kecak dansı, sörf dersleri ve son üç gece Seminyak'taki lüks resort konaklaması.",
    included: ["Uçak bileti", "7 gece konaklama (3 gece Ubud villa, 4 gece Seminyak resort)", "Kahvaltılar", "Özel araç ve sürücü (tüm geziler)", "Bali vize desteği", "Rehber"],
    excluded: ["Sörf dersi (isteğe bağlı, €40/gün)", "Spa ve masaj", "Öğle/akşam yemekleri"],
    highlights: ["Tegallalang Pirinç Terasları", "Tanah Lot Tapınağı günbatımı", "Ubud Maymun Ormanı", "Kecak Ateş Dansı"],
    availableDates: ["10 Haziran 2026", "1 Temmuz 2026", "15 Temmuz 2026", "5 Ağustos 2026"],
    gallery: ["Tegallalang Pirinç Terasları", "Tanah Lot Günbatımı", "Ubud Villa", "Seminyak Plajı"],
    faq: [
      { q: "Bali vizesi gerekiyor mu?", a: "Türk vatandaşları 30 güne kadar vizesiz giriş yapabilir. Uzun süreli kalış için VOA (Vize on Arrival) gerekebilir; rehberimiz yönlendirir." },
    ],
    groupSize: "Maks. 12 kişi",
    difficulty: "Orta",
  },
  {
    slug: "dubai-lüks",
    name: "Dubai — Lüks & Çöl Safarisi",
    destination: "Dubai",
    country: "BAE",
    region: "Orta Doğu",
    duration: "4 Gece / 5 Gün",
    nights: 4,
    price: 1300,
    currency: "EUR",
    badge: "Bestseller",
    rating: 4.7,
    reviews: 198,
    summary: "Burj Khalifa, Dubai Mall, lüks otel ve çöl safarisiyle Dubai'nin görkemli dünyası.",
    description: "Dünyanın en yüksek binası Burj Khalifa'da gün batımı, Palm Jumeirah turları, altın çarşıları ve akşam çöl safarisiyle 5 gün. Tüm vize işlemleri Orion Travel tarafından yönetilir.",
    included: ["Uçak bileti", "4 gece 5 yıldızlı otel", "Vize işlemleri", "Şehir turu", "Çöl safarisi (barbekü dahil)", "Tüm transferler"],
    excluded: ["Dubai Mall alışveriş harcamaları", "Ekstra turlar", "Kişisel harcamalar"],
    highlights: ["Burj Khalifa At The Top", "Çöl safarisi ve deve binme", "Palm Jumeirah turu", "Dubai Çarşısı ve Altın Çarşısı"],
    availableDates: ["20 Nisan 2026", "4 Mayıs 2026", "18 Mayıs 2026", "15 Haziran 2026", "20 Temmuz 2026"],
    gallery: ["Burj Khalifa Panorama", "Çöl Safarisi Gün Batımı", "Palm Jumeirah Havadan", "Dubai Marina Geceleri"],
    faq: [
      { q: "Vize süreci ne kadar sürer?", a: "Dubai vizesi genellikle 3–5 iş günü içinde çıkar. Orion Travel tüm evrak sürecini yönetir." },
    ],
    groupSize: "Maks. 20 kişi",
    difficulty: "Kolay",
  },
  {
    slug: "antalya-all-inclusive",
    name: "Antalya — 5 Yıldız All Inclusive Tatil",
    destination: "Antalya",
    country: "Türkiye",
    region: "Yurt İçi",
    duration: "4 Gece / 5 Gün",
    nights: 4,
    price: 9500,
    currency: "TRY",
    badge: undefined,
    rating: 4.6,
    reviews: 312,
    summary: "Antalya'nın berrak denizinde 5 yıldızlı konfor, tam pansiyon tatil ve antik kent gezileri.",
    description: "Antalya'nın en iyi all-inclusive resortlarından birinde 5 gün. Havuz başı dinlence, berrak Akdeniz kıyısı, sınırsız yeme-içme ve opsiyonel antik kent turları (Aspendos, Perge, Manavgat) ile unutulmaz bir tatil.",
    included: ["Uçak bileti", "4 gece 5 yıldızlı otel (all inclusive)", "Havalimanı transferleri", "Animasyon programı"],
    excluded: ["Spa hizmetleri", "Ekstra turlar", "Mini bar"],
    highlights: ["Sınırsız yeme-içme", "Aquapark dahil", "Aspendos Antik Tiyatrosu gezisi", "Manavgat Şelalesi turu"],
    availableDates: ["1 Haziran 2026", "15 Haziran 2026", "1 Temmuz 2026", "15 Temmuz 2026", "1 Ağustos 2026"],
    gallery: ["Resort Havuz Alanı", "Plaj Manzarası", "Aspendos Tiyatrosu", "Manavgat Şelalesi"],
    faq: [
      { q: "Çocuklar için aktivite var mı?", a: "Evet. Seçilen oteller çocuk kulübü, mini havuz ve animasyon programlarıyla donatılmıştır." },
    ],
    groupSize: "Maks. 40 kişi",
    difficulty: "Kolay",
  },
  {
    slug: "prag-orta-cag",
    name: "Prag & Çek Cumhuriyeti Kültür Turu",
    destination: "Prag",
    country: "Çekya",
    region: "Avrupa",
    duration: "4 Gece / 5 Gün",
    nights: 4,
    price: 880,
    currency: "EUR",
    rating: 4.8,
    reviews: 76,
    summary: "Orta Çağ kalesi, Karlov Köprüsü ve Çesky Krumlov güzelliğiyle Prag.",
    description: "Avrupa'nın en güzel şehirlerinden Prag'ın gotik kalesi, tarihi meydanları ve taş döşemeli sokaklarında 5 gün. Günübirlik Çesky Krumlov ziyareti ve bira festivali dahildir.",
    included: ["Uçak bileti", "4 gece butik otel (4*)", "Günlük kahvaltı", "Profesyonel rehber", "Çesky Krumlov günü", "Schengen vize desteği"],
    excluded: ["Yemekler (kahvaltı hariç)", "Müze girişleri", "Kişisel harcamalar"],
    highlights: ["Prag Kalesi turu", "Karlov Köprüsü", "Eski Şehir Meydanı", "Çesky Krumlov kasabası"],
    availableDates: ["25 Nisan 2026", "9 Mayıs 2026", "23 Mayıs 2026", "13 Haziran 2026"],
    gallery: ["Prag Kalesi Panorama", "Karlov Köprüsü Geceleri", "Eski Şehir Meydanı", "Çesky Krumlov"],
    faq: [
      { q: "Schengen vizem yok, katılabilir miyim?", a: "Vize desteği sunuyoruz. Başvuru için pasaport + banka dökümü yeterlidir; süreç 7–10 iş günüdür." },
    ],
    groupSize: "Maks. 18 kişi",
    difficulty: "Kolay",
  },
  {
    slug: "safari-kenya",
    name: "Kenya Safari — Büyük Göç",
    destination: "Masai Mara",
    country: "Kenya",
    region: "Afrika",
    duration: "7 Gece / 8 Gün",
    nights: 7,
    price: 2800,
    currency: "EUR",
    badge: "Son Kontenjan",
    rating: 5.0,
    reviews: 29,
    summary: "Büyük Göç'e tanıklık, Masai Mara'da kamp geceleri ve Nairobi şehir turu.",
    description: "Dünyanın en muhteşem vahşi yaşam gösterisine — Büyük Göç'e — sahaya inerek tanıklık edin. Masai Mara'da çadır kamp konaklaması, sabah safari jeep turları, Masai köyü ziyareti ve Nairobi'de son gece.",
    included: ["Uçak bileti (İstanbul–Nairobi)", "7 gece konaklama (4 kamp, 3 Nairobi oteli)", "Tüm safariler ve park ücretleri", "Tam pansiyon", "Profesyonel safari rehberi"],
    excluded: ["Seyahat sigortası (zorunlu)", "İsteğe bağlı balon safarisi (€450)", "Bahşişler"],
    highlights: ["Büyük Göç geçişi", "Büyük Beşliler (fil, aslan, leopar, buffalo, gergedan)", "Masai köyü ziyareti", "Nairobi Ulusal Müzesi"],
    availableDates: ["15 Temmuz 2026", "1 Ağustos 2026", "15 Ağustos 2026"],
    gallery: ["Aslan Ailesi Sabah Işığı", "GNU Geçişi Mara Nehri", "Kamp Geceleri Gökyüzü", "Masai Dansı"],
    faq: [
      { q: "Büyük Göç ne zaman gerçekleşiyor?", a: "Temmuz–Ekim ayları Masai Mara'da GNU geçişi için en iyi dönemdir. Turlarımız bu döneme planlanmıştır." },
      { q: "Seyahat sigortası zorunlu mu?", a: "Evet. Safari turlarında medikal tahliye dahil seyahat sigortası zorunludur; temin konusunda yardımcı oluyoruz." },
    ],
    groupSize: "Maks. 10 kişi",
    difficulty: "Orta",
  },
  {
    slug: "japonya-kiraz-cicegi",
    name: "Japonya — Kiraz Çiçeği & Kültür",
    destination: "Tokyo & Kyoto",
    country: "Japonya",
    region: "Uzak Doğu",
    duration: "10 Gece / 11 Gün",
    nights: 10,
    price: 3200,
    currency: "EUR",
    badge: "Yeni",
    rating: 4.9,
    reviews: 38,
    summary: "Tokyo'nun modernliği, Kyoto'nun geleneksel mahalleleri ve kiraz çiçeği mevsimi.",
    description: "Japonya'nın iki başkentini; teknolojinin merkezi Tokyo ile tarihin kalbi Kyoto'yu kiraz çiçeği mevsiminde keşfedin. Nara geyikleri, Fushimi Inari tapınağı, Shinkansen deneyimi ve gerçek bir ryokan gecesi.",
    included: ["Uçak bileti", "10 gece konaklama (7 otel, 1 gece ryokan)", "JR Pass (7 günlük)", "Tokyo ve Kyoto şehir turları", "Rehber"],
    excluded: ["Yemekler (kahvaltı hariç)", "Tekil aktiviteler", "Kişisel harcamalar"],
    highlights: ["Fushimi Inari Taisha tapınağı", "Nara Geyik Parkı", "Shinjuku Gyoen kiraz çiçeği", "Shinkansen Tokyo–Kyoto"],
    availableDates: ["25 Mart 2027", "1 Nisan 2027"],
    gallery: ["Kiraz Çiçeği Tokyo Parkı", "Fushimi Inari Torii Kapıları", "Ryokan Odası", "Shibuya Kavşağı"],
    faq: [
      { q: "Kiraz çiçeği garantili mi?", a: "Japonya'da kiraz çiçeği Mart sonu – Nisan başında açar. Tur tarihleri bu döneme göre planlanmış olsa da doğa koşulları değişkenlik gösterebilir." },
    ],
    groupSize: "Maks. 14 kişi",
    difficulty: "Orta",
  },
  {
    slug: "amalfi-italya",
    name: "Amalfi Kıyısı & Roma Turu",
    destination: "Amalfi, Roma",
    country: "İtalya",
    region: "Avrupa",
    duration: "6 Gece / 7 Gün",
    nights: 6,
    price: 1450,
    currency: "EUR",
    badge: undefined,
    rating: 4.8,
    reviews: 63,
    summary: "Amalfi'nin dramatik kıyıları, Pompei harabeleri ve Roma'nın efsanevi tarihi.",
    description: "İtalya'nın en özel iki bölgesini tek turda keşfedin. Napoli uçuşu, Pompei ve Herculaneum antik kentleri, Amalfi kıyı şeridi tekne turu, Capri adası ve son 2 gece Roma'da Colosseum, Vatikan ve Trevi Çeşmesi.",
    included: ["Uçak bileti (İstanbul–Napoli, Roma–İstanbul)","6 gece otel", "Günlük kahvaltı", "Pompei rehberli tur", "Amalfi tekne turu", "Roma şehir turu"],
    excluded: ["Capri günü feribot ücreti (€30)", "Müze girişleri", "Yemekler"],
    highlights: ["Pompei & Herculaneum antik kentleri", "Amalfi kıyı tekne turu", "Capri Mavi Mağara", "Roma Vatikan & Colosseum"],
    availableDates: ["20 Nisan 2026", "11 Mayıs 2026", "1 Haziran 2026", "22 Haziran 2026"],
    gallery: ["Amalfi Kıyı Panorama", "Pompei Antik Sokakları", "Roma Colosseum", "Capri Mavi Mağara"],
    faq: [
      { q: "Schengen vize süreci nasıl?", a: "İtalya Büyükelçiliği'ne başvuru gereklidir; Orion Travel danışmanlık sunar. Süreç 10–15 iş günüdür." },
    ],
    groupSize: "Maks. 16 kişi",
    difficulty: "Orta",
  },
  {
    slug: "new-york-klasik",
    name: "New York — Klasik Şehir Turu",
    destination: "New York",
    country: "ABD",
    region: "Amerika",
    duration: "6 Gece / 7 Gün",
    nights: 6,
    price: 2100,
    currency: "EUR",
    badge: undefined,
    rating: 4.7,
    reviews: 91,
    summary: "Manhattan, Central Park, Özgürlük Heykeli ve Broadway ile New York'u keşfedin.",
    description: "Dünyanın en ikonik şehrinde 7 gün. Manhattan yürüyüşleri, Özgürlük Heykeli feribot turu, Central Park bisiklet kiralama, MoMA müzesi ve bir Broadway gösterisi. Vize işlemleri dahildir.",
    included: ["Uçak bileti", "6 gece Manhattan oteli (4*)", "ESTA/vize desteği", "Şehir turu", "Özgürlük Heykeli feribot turu", "1 Broadway bileti"],
    excluded: ["Yemekler", "Müze girişleri (MoMA dahil değil)", "Kişisel alışveriş"],
    highlights: ["Times Square & Broadway", "Central Park bisiklet turu", "Özgürlük Heykeli", "Top of the Rock manzara terası"],
    availableDates: ["10 Mayıs 2026", "7 Haziran 2026", "5 Temmuz 2026", "2 Ağustos 2026"],
    gallery: ["Manhattan Skyline Geceleri", "Özgürlük Heykeli", "Central Park Sonbahar", "Times Square"],
    faq: [
      { q: "ABD vizesi ne kadar sürer?", a: "ESTA başvurusu 72 saat içinde sonuçlanır. B1/B2 vize gerekiyorsa 4–8 hafta olabilir; erken başvuru önerilir." },
    ],
    groupSize: "Maks. 20 kişi",
    difficulty: "Kolay",
  },
];

export function getTour(slug: string): TourPackage | undefined {
  return TOURS.find((t) => t.slug === slug);
}

export function formatPrice(price: number, currency: string): string {
  if (currency === "TRY") return "₺" + price.toLocaleString("tr-TR");
  if (currency === "EUR") return "€ " + price.toLocaleString("tr-TR");
  return "$ " + price.toLocaleString("tr-TR");
}
